### ISSUE TITLE
Setting up a simple connection..

### ISSUE THREAD

**Issue by shadowwolf0189** [loldevs/riotapi#38]
Greetings!
I apologize in advance for the sideways question, but you're one of the few people I can find that are continuing work on the XMPP side of League.

I'm trying to setup a basic connection to the chat servers. Here is what I've tried; http://pastie.org/private/qkpvx0jwl3ghclf246sg

However I'm stuck with two errors:
(1) org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: chat.na2.lol.riotgames.com:5223 Exception: null
(2) Server did not report any SASL mechanisms

I should point out that I've tried both na1 and na2. 

Again I apologize for contacting you here but I could not find an e-mail or anything else withwhich to do so. Any help is appreciated! Vielen Dank!

-Steve

**Comment by Boreeas** [comment]
Hi. What we did was set the security mode to "disabled" (https://github.com/loldevs/riotapi/blob/master/xmpp/src/main/java/net/boreeas/xmpp/XmppClient.java#L64). This seems to fix those errors while still enabling SSL connections

**Comment by shadowwolf0189** [comment]
Hey, thank you for the fast response! I have tried both enabling and disabling the SecurityMode to no avail on either end.

**Comment by Boreeas** [comment]
Hmm. Did you try disabling compression? Do other servers (e.g. EUW) work?

**Comment by shadowwolf0189** [comment]
I get the same two errors regardless of hostname and/or compression type.

**Comment by shadowwolf0189** [comment]
I'm trying to do this on Android. I will try it on my PC and report back if it's any different.

**Comment by shadowwolf0189** [comment]
Tried it and got an SASLErrorException, using the code here: http://pastie.org/private/naypfuktfypqqnwo8uquva

Tried enabling/disabling Compression and SecurityMode. 

Relevant error:
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using PLAIN: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:348)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.login(XMPPTCPConnection.java:244)

And the error line is connection.login()

**Comment by Boreeas** [comment]
Could it be that this is a problem with whatever library you are using on Android? I can't see any problem with your code, sorry.

**Comment by shadowwolf0189** [comment]
It was! I'm sorry it took long for me to get back. I downgraded to aSmack 0.8, released around March 20'th, and I have success. Thank you again for your time!

**Comment by Boreeas** [comment]
Great to hear that! (fwiw, that might be something that the smack guys might be interested in, too. Maybe you should tell someone on IRC, since the project doesn't seem to have a github repository)
