### ISSUE TITLE
XmppClient sendToChannel not working

### ISSUE THREAD

**Issue by Kab00se** [loldevs/riotapi#41]
The sendToChannel(String channel, String message) is not actually sending the message to channel.

I join using "MultiUserChat muc = getXmppClient().joinChannel("MyBotChannel", ChatType.PUBLIC, null);"

I then add a PacketListener to muc which simply writes a message upon receiving a message, like so: 

// body of processPacket(Packet packet) throws NotConnectedException
Message msg = (Message) packet;
if (msg.getBody() != null) {
    System.out.println(msg.toString());
    System.out.println("Message: " + msg.getBody());
    try {
	bot.getXmppClient().sendToChannel("MyBotChannel", "Test message from bot.");
} // Catch here

I am receiving the packets/messages just fine.

**Comment by Boreeas** [comment]
Is your bot a sufficiently high level? You need to be >= level 5 to send message to public chatrooms

**Comment by Kab00se** [comment]
Didn't they lift that restriction? When I log in manually I can join/send messages without issue.

**Comment by Boreeas** [comment]
I justed tested it and can confirm that a level 1 account can't send to a public chat
