### ISSUE TITLE
LoginFailedException

### ISSUE THREAD

**Issue by kevorski** [loldevs/riotapi#42]
Trying to access the NA server, whenever I run the program and I use my login credentials I get

LoginFailedException(bannedUntilDate=Wed Dec 31 16:00:00 PST 1969)

My account isn't banned.

Maybe I have it setup incorrectly but just going off what I have right now.

**Comment by molenzwiebel** [comment]
Getting the same problem. What did you do to fix it?

**Comment by jaagupkymmel** [comment]
Also getting the same error.

**Comment by Boreeas** [comment]
So the problem is apparently the new login queue system. I've tested 1.6.0, which is the last version using the old system, and it works fine, so I'll be porting that back to 2.x.

... as soon as I find the time

**Comment by jaagupkymmel** [comment]
So it should work with 1.6.0?

**Comment by Boreeas** [comment]
1.6.0 worked for me, but I heard stories of people saying they are getting exceptions

**Comment by jaagupkymmel** [comment]
I'll give it a go!

**Comment by Boreeas** [comment]
So, version 2.0.4 should fix the problem. Just wait a couple of hours for maven central to pick up on the upload
